# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen/ui_designer/screen_resumo_livro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(640, 480)
        Form.setMaximumSize(QtCore.QSize(640, 480))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lstUser = QtWidgets.QListWidget(Form)
        self.lstUser.setGeometry(QtCore.QRect(30, 130, 251, 241))
        self.lstUser.setObjectName("lstUser")
        self.btAdicionarUsuario = QtWidgets.QPushButton(Form)
        self.btAdicionarUsuario.setGeometry(QtCore.QRect(420, 180, 121, 51))
        self.btAdicionarUsuario.setObjectName("btAdicionarUsuario")
        self.txtNovoUsuario = QtWidgets.QLineEdit(Form)
        self.txtNovoUsuario.setGeometry(QtCore.QRect(420, 140, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtNovoUsuario.setFont(font)
        self.txtNovoUsuario.setObjectName("txtNovoUsuario")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(420, 120, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btExcluirUsuario = QtWidgets.QPushButton(Form)
        self.btExcluirUsuario.setGeometry(QtCore.QRect(160, 380, 121, 51))
        self.btExcluirUsuario.setObjectName("btExcluirUsuario")
        self.btEditarUsuario = QtWidgets.QPushButton(Form)
        self.btEditarUsuario.setGeometry(QtCore.QRect(30, 380, 121, 51))
        self.btEditarUsuario.setObjectName("btEditarUsuario")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CADASTRO DE USUÁRIOS"))
        self.btAdicionarUsuario.setText(_translate("Form", "Adicionar usuário"))
        self.label_2.setText(_translate("Form", "Novo usuário"))
        self.label_3.setText(_translate("Form", "Usuários cadastrados"))
        self.btExcluirUsuario.setText(_translate("Form", "Excluir"))
        self.btEditarUsuario.setText(_translate("Form", "Editar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
