# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen/ui_designer/screen_resumo_livro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 864)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 1261, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lbTituloLivro = QtWidgets.QLabel(Form)
        self.lbTituloLivro.setGeometry(QtCore.QRect(10, 50, 1251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbTituloLivro.setFont(font)
        self.lbTituloLivro.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTituloLivro.setObjectName("lbTituloLivro")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(970, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.cbUsuario = QtWidgets.QComboBox(Form)
        self.cbUsuario.setGeometry(QtCore.QRect(970, 110, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbUsuario.setFont(font)
        self.cbUsuario.setObjectName("cbUsuario")
        self.btBuscarResumos = QtWidgets.QPushButton(Form)
        self.btBuscarResumos.setGeometry(QtCore.QRect(1176, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btBuscarResumos.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("screen/ui_designer\\../../resources/icons/search_24dp_5F6368.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btBuscarResumos.setIcon(icon)
        self.btBuscarResumos.setIconSize(QtCore.QSize(24, 24))
        self.btBuscarResumos.setObjectName("btBuscarResumos")
        self.lbStatus = QtWidgets.QLabel(Form)
        self.lbStatus.setGeometry(QtCore.QRect(10, 840, 1251, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbStatus.setFont(font)
        self.lbStatus.setObjectName("lbStatus")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 160, 1271, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Titiulo = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Titiulo.setFont(font)
        self.Titiulo.setObjectName("Titiulo")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Titiulo.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Titiulo.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.Titiulo)

        self.retranslateUi(Form)
        self.Titiulo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Resumo do Livro"))
        self.label.setText(_translate("Form", "RESUMO DO LIVRO"))
        self.lbTituloLivro.setText(_translate("Form", "LIVRO XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"))
        self.label_4.setText(_translate("Form", "Usuário:"))
        self.btBuscarResumos.setText(_translate("Form", "Buscar"))
        self.lbStatus.setText(_translate("Form", "lbStatus"))
        self.Titiulo.setTabText(self.Titiulo.indexOf(self.tab), _translate("Form", "Cadastrar Resumo"))
        self.Titiulo.setTabText(self.Titiulo.indexOf(self.tab_2), _translate("Form", "Ler Resumo Completo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
