# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen/ui_designer/screen02_tela_teste.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(350, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 40, 381, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_valor1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_valor1.setObjectName("txt_valor1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_valor1)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_valor2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_valor2.setObjectName("txt_valor2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_valor2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txt_valor3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_valor3.setObjectName("txt_valor3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_valor3)
        self.lb_resposta = QtWidgets.QLabel(Form)
        self.lb_resposta.setGeometry(QtCore.QRect(30, 270, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lb_resposta.setFont(font)
        self.lb_resposta.setObjectName("lb_resposta")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "OK"))
        self.label.setText(_translate("Form", "valor 1"))
        self.txt_valor1.setText(_translate("Form", "100"))
        self.label_2.setText(_translate("Form", "valor 2"))
        self.txt_valor2.setText(_translate("Form", "200"))
        self.label_3.setText(_translate("Form", "valor 3"))
        self.txt_valor3.setText(_translate("Form", "300"))
        self.lb_resposta.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
