del D:\python_projetos\MinhaBiblioteca\screen\generated\__pycache__\*.*
rmdir D:\python_projetos\MinhaBiblioteca\screen\generated\__pycache__
del D:\python_projetos\MinhaBiblioteca\test\__pycache__\*.*
rmdir D:\python_projetos\MinhaBiblioteca\test\__pycache__
del D:\python_projetos\MinhaBiblioteca\screen\controllers\__pycache__\*.*
rmdir D:\python_projetos\MinhaBiblioteca\screen\controllers\__pycache__
del D:\python_projetos\MinhaBiblioteca\screen\controllers\__pycache__\*.*
rmdir D:\python_projetos\MinhaBiblioteca\screen\controllers\__pycache__
del D:\python_projetos\MinhaBiblioteca\models\__pycache__\*.*
rmdir D:\python_projetos\MinhaBiblioteca\models\__pycache__
del D:\python_projetos\MinhaBiblioteca\database\__pycache__\*.*
rmdir D:\python_projetos\MinhaBiblioteca\database\__pycache__
del D:\python_projetos\MinhaBiblioteca\database\crud\__pycache__\*.*
rmdir D:\python_projetos\MinhaBiblioteca\database\crud\__pycache__
del D:\python_projetos\MinhaBiblioteca\utils\__pycache__\*.*
rmdir D:\python_projetos\MinhaBiblioteca\utils\__pycache__